### ISSUE TITLE
AODA

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/citizenbudgetapp.com#4]
https://github.com/opennorth/citizenbudgetapp.com/issues/59

**Comment by lharv076** [comment]
@claudioccm Heya,

When are you ready to deploy this?

**Comment by gmattar** [comment]
The commit d4f0c3c addresses this issue and already is in a pull request (https://github.com/opennorth/citizenbudgetapp.com/pull/98). I can send a separate PR if you want. 
However, it doesn't fix the slider problem, I'm still working on it.

**Comment by lharv076** [comment]
Ok great, we will deploy opennorth#98 tomorrow and start testing the feature.
